# Generated by Django 3.1.2 on 2020-11-27 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyFaits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fromcurrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromcurrency', to='currency.currency')),
                ('tocurrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tocurrency', to='currency.currency')),
            ],
        ),
    ]
