# Generated by Django 3.1.2 on 2020-11-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyfaits',
            name='conversionFactor',
            field=models.FloatField(default=0.0),
        ),
    ]
