# Generated by Django 3.1.2 on 2020-11-26 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password1',
            new_name='confirmpassword',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password2',
            new_name='password',
        ),
    ]
